env:
  browser: true
  es6: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 11
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - "react"
extends:
  - "eslint:recommended"
rules:
  react/jsx-uses-vars: "error"
  react/jsx-uses-react: "error"
  react/jsx-key: "warn"
  react/jsx-no-comment-textnodes: "error"
  react/jsx-no-duplicate-props: "error"
  react/jsx-no-target-blank: "error"
  react/jsx-no-undef: "error"
